/**********************************************************************************************************************
 * \file ASCLIN_Shell_UART.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "ASCLIN_Shell_UART.h"
#include "Ifx_Types.h"
#include "IfxAsclin_Asc.h"
#include "Ifx_Shell.h"
#include "Ifx_Console.h"
#include "IfxPort.h"
#include "stdint.h"
#include "CommunicationApp.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/* Communication parameters */
#define ISR_PRIORITY_ASCLIN_TX      (0x8)                                       /* Priority for interrupt ISR Transmit  */
#define ISR_PRIORITY_ASCLIN_RX      (0x4)                                       /* Priority for interrupt ISR Receive   */
#define ISR_PRIORITY_ASCLIN_ER      (0xC)                                      /* Priority for interrupt ISR Errors    */
#define ASC_TX_BUFFER_SIZE          (0x100)                                     /* Define the TX buffer size in byte    */
#define ASC_RX_BUFFER_SIZE          (0x100)                                     /* Define the RX buffer size in byte    */
#define ASC_BAUDRATE                (115200)                                  /* Define the UART baud rate            */

#define ASCLIN1_TX0     (IfxAsclin1_TX_P15_0_OUT)
#define ASCLIN1_RX0     (IfxAsclin1_RXA_P15_1_IN)
#define ASCLIN2_TX1     (IfxAsclin2_TX_P33_9_OUT)
#define ASCLIN2_RX1     (IfxAsclin2_RXE_P33_8_IN)
#define ASCLIN3_TX2     (IfxAsclin3_TX_P20_0_OUT)
#define ASCLIN3_RX2     (IfxAsclin3_RXC_P20_3_IN)

#define ISR_PRIORITY_ASCLIN_TX0      (0x88)                                        /* Priority for interrupt ISR Transmit  */
#define ISR_PRIORITY_ASCLIN_RX0      (0x84)                                        /* Priority for interrupt ISR Receive   */
#define ISR_PRIORITY_ASCLIN_ER0      (0x8C)                                        /* Priority for interrupt ISR Errors    */
#define ISR_PRIORITY_ASCLIN_TX1      (0x98)                                        /* Priority for interrupt ISR Transmit  */
#define ISR_PRIORITY_ASCLIN_RX1      (0x94)                                        /* Priority for interrupt ISR Receive   */
#define ISR_PRIORITY_ASCLIN_ER1      (0x9C)                                        /* Priority for interrupt ISR Errors    */
#define ISR_PRIORITY_ASCLIN_TX2      (0xA8)                                        /* Priority for interrupt ISR Transmit  */
#define ISR_PRIORITY_ASCLIN_RX2      (0xA4)                                        /* Priority for interrupt ISR Receive   */
#define ISR_PRIORITY_ASCLIN_ER2      (0xAC)                                        /* Priority for interrupt ISR Errors    */

typedef struct UartInterface {
    IfxAsclin_Asc* asclin;
    Ifx_ASCLIN* module;
    uint16 txPriority;
    uint16 rxPriority;
    IfxAsclin_Rx_In* rxPin;
    IfxAsclin_Tx_Out* txPin;
    uint8 txBuffer[ASC_TX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];
    uint8 rxBuffer[ASC_RX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];
}UartInterface_t;

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
static void initSerialInterface(int uartNum);
static char convertDecToHexAscii(uint8_t x);

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
static IfxAsclin_Asc   g_asclin;                                                   /* ASCLIN module object                 */
static IfxAsclin_Asc   asclin0;                                                   /* ASCLIN module object                 */
static IfxAsclin_Asc   asclin1;                                                   /* ASCLIN module object                 */
static IfxAsclin_Asc   asclin2;                                                   /* ASCLIN module object                 */

static const txBufferSize = ASC_TX_BUFFER_SIZE;
static const rxBufferSize = ASC_RX_BUFFER_SIZE;


UartInterface_t uartInterfaces[] = {
        {&g_asclin, &MODULE_ASCLIN3, ISR_PRIORITY_ASCLIN_TX, ISR_PRIORITY_ASCLIN_RX, &IfxAsclin3_RXD_P32_2_IN, &IfxAsclin3_TX_P15_7_OUT},
        {&asclin0, &MODULE_ASCLIN1, ISR_PRIORITY_ASCLIN_TX0, ISR_PRIORITY_ASCLIN_RX0, &ASCLIN1_RX0, &ASCLIN1_TX0},
        {&asclin1, &MODULE_ASCLIN2, ISR_PRIORITY_ASCLIN_TX1, ISR_PRIORITY_ASCLIN_RX1, &ASCLIN2_RX1, &ASCLIN2_TX1},
        {&asclin2, &MODULE_ASCLIN3, ISR_PRIORITY_ASCLIN_TX2, ISR_PRIORITY_ASCLIN_RX2, &ASCLIN3_RX2, &ASCLIN3_TX2},
        //{&asclin2, &MODULE_ASCLIN3, ISR_PRIORITY_ASCLIN_TX2, ISR_PRIORITY_ASCLIN_RX2, &ASCLIN3_RX2, &ASCLIN3_TX2}
};

/* The transfer buffers allocate memory for the data itself and for FIFO runtime variables.
 * 8 more bytes have to be added to ensure a proper circular buffer handling independent from
 * the address to which the buffers have been located.
 */

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/* Macro to define Interrupt Service Routine.
 * This macro makes following definitions:
 * 1) Define linker section as .intvec_tc<vector number>_<interrupt priority>.
 * 2) define compiler specific attribute for the interrupt functions.
 * 3) define the Interrupt service routine as ISR function.
 *
 * IFX_INTERRUPT(isr, vectabNum, priority)
 *  - isr: Name of the ISR function.
 *  - vectabNum: Vector table number.
 *  - priority: Interrupt priority. Refer Usage of Interrupt Macro for more details.
 */
IFX_INTERRUPT(asc0TxISR, 0, ISR_PRIORITY_ASCLIN_TX);

void asc0TxISR(void)
{
    IfxAsclin_Asc_isrTransmit(uartInterfaces[0].asclin);
}

IFX_INTERRUPT(asc0RxISR, 0, ISR_PRIORITY_ASCLIN_RX);

void asc0RxISR(void)
{
    int cnt = 1;
    uint8_t buf[2] = { 0, };

    IfxAsclin_Asc_isrReceive(uartInterfaces[0].asclin);
    IfxAsclin_Asc_read(uartInterfaces[0].asclin, buf, &cnt, 100);

    if (buf[0] == 0xff)
    {
        forwardMessage(DEVICE_TERMINAL);
    }
    else
    {
        saveMessage(DEVICE_TERMINAL, buf[0]);
    }
}

IFX_INTERRUPT(isrUartTx0, 0, ISR_PRIORITY_ASCLIN_TX0);

void isrUartTx0(void)
{
    IfxAsclin_Asc_isrTransmit(uartInterfaces[1].asclin);
}

IFX_INTERRUPT(isrUartRx0, 0, ISR_PRIORITY_ASCLIN_RX0);

void isrUartRx0(void)
{
    int cnt = 1;
    uint8_t buf[2] = { 0, };
    IfxAsclin_Asc_isrReceive(uartInterfaces[1].asclin);
    IfxAsclin_Asc_read(uartInterfaces[1].asclin, buf, &cnt, 100);

    if (buf[0] == 0xff) {
        forwardMessage(DEVICE_STM32);
    }
    else {
        saveMessage(DEVICE_STM32, buf[0]);
    }

    cnt = 1;
    printUart(&buf, &cnt);
}

IFX_INTERRUPT(isrUartTx1, 0, ISR_PRIORITY_ASCLIN_TX1);

void isrUartTx1(void)
{
    IfxAsclin_Asc_isrTransmit(uartInterfaces[2].asclin);
}

IFX_INTERRUPT(isrUartRx1, 0, ISR_PRIORITY_ASCLIN_RX1);

void isrUartRx1(void)
{
    int cnt = 1;
    uint8_t buf[2] = { 0, };
    IfxAsclin_Asc_isrReceive(uartInterfaces[2].asclin);
    IfxAsclin_Asc_read(uartInterfaces[2].asclin, buf, &cnt, 100);

    if (buf[0] == 0xff) {
        forwardMessage(DEVICE_RPI);
    }
    else {
        saveMessage(DEVICE_RPI, buf[0]);
    }


    cnt = 1;
    printUart(&buf, &cnt);
}

IFX_INTERRUPT(isrUartTx2, 0, ISR_PRIORITY_ASCLIN_TX2);

void isrUartTx2(void)
{
    IfxAsclin_Asc_isrTransmit(uartInterfaces[3].asclin);
}

IFX_INTERRUPT(isrUartRx2, 0, ISR_PRIORITY_ASCLIN_RX2);

void isrUartRx2(void)
{
    int cnt = 1;
    uint8_t buf[2] = { 0, };
    IfxAsclin_Asc_isrReceive(uartInterfaces[3].asclin);
    IfxAsclin_Asc_read(uartInterfaces[3].asclin, buf, &cnt, 100);

    if (buf[0] == 0xff) {
        forwardMessage(DEVICE_WROOM);
    }
    else {
        saveMessage(DEVICE_WROOM, buf[0]);
    }


    cnt = 1;
    printUart(&buf, &cnt);
}

/* Function to initialize ASCLIN module */
static void initSerialInterface(int uartNum)
{
    IfxAsclin_Asc_Config ascConf;

    /* Set default configurations */
    IfxAsclin_Asc_initModuleConfig(&ascConf, uartInterfaces[uartNum].module); /* Initialize the structure with default values      */

    /* Set the desired baud rate */
    ascConf.baudrate.baudrate = ASC_BAUDRATE;                                   /* Set the baud rate in bit/s       */
    ascConf.baudrate.oversampling = IfxAsclin_OversamplingFactor_16;            /* Set the oversampling factor      */

    /* Configure the sampling mode */
    ascConf.bitTiming.medianFilter = IfxAsclin_SamplesPerBit_three;             /* Set the number of samples per bit*/
    ascConf.bitTiming.samplePointPosition = IfxAsclin_SamplePointPosition_8;    /* Set the first sample position    */

    /* ISR priorities and interrupt target */
    ascConf.interrupt.txPriority = uartInterfaces[uartNum].txPriority;  /* Set the interrupt priority for TX events             */
    ascConf.interrupt.rxPriority = uartInterfaces[uartNum].rxPriority;  /* Set the interrupt priority for RX events             */
    ascConf.interrupt.typeOfService = IfxSrc_Tos_cpu0;

    /* Pin configuration */
    const IfxAsclin_Asc_Pins pins = {
            .cts        = NULL_PTR,                         /* CTS pin not used                                     */
            .ctsMode    = IfxPort_InputMode_pullUp,
            .rx         = uartInterfaces[uartNum].rxPin,        /* Select the pin for RX connected to the USB port      */
            .rxMode     = IfxPort_InputMode_pullUp,         /* RX pin                                               */
            .rts        = NULL_PTR,                         /* RTS pin not used                                     */
            .rtsMode    = IfxPort_OutputMode_pushPull,
            .tx         = uartInterfaces[uartNum].txPin,         /* Select the pin for TX connected to the USB port      */
            .txMode     = IfxPort_OutputMode_pushPull,      /* TX pin                                               */
            .pinDriver  = IfxPort_PadDriver_cmosAutomotiveSpeed1
    };
    ascConf.pins = &pins;

    /* FIFO buffers configuration */
    ascConf.txBuffer = uartInterfaces[uartNum].txBuffer;                      /* Set the transmission buffer                          */
    ascConf.txBufferSize = ASC_TX_BUFFER_SIZE;              /* Set the transmission buffer size                     */
    ascConf.rxBuffer = uartInterfaces[uartNum].rxBuffer;                      /* Set the receiving buffer                             */
    ascConf.rxBufferSize = ASC_RX_BUFFER_SIZE;              /* Set the receiving buffer size                        */

    /* Init ASCLIN module */
    IfxAsclin_Asc_initModule(uartInterfaces[uartNum].asclin, &ascConf);          /* Initialize the module with the given configuration   */
}

void initUartInterface(void) {
    for (int i = 0; i < 3; i++) {
        initSerialInterface(i);
    }
}

void sendUart(int uartNum, const void* data, Ifx_SizeT* dataSize) {
    if (uartNum < 0 || uartNum > 3) {
        int x = 5;
        IfxAsclin_Asc_write(uartInterfaces[0].asclin, "FUCK?", &x, TIME_INFINITE);
        return;
    }

    if (uartNum > 0) {
        IfxAsclin_Asc_write(uartInterfaces[uartNum].asclin, data, dataSize, TIME_INFINITE);
    }
}

void printUart(const void* data, Ifx_SizeT* dataSize) {
    uint8_t* data_byte = (uint8_t *)data;
    for (int i = 0; i < *dataSize; i++) {
        int cnt = 5;
        char byteToHex[5] = "0x";
        byteToHex[2] = convertDecToHexAscii(data_byte[i] >> 4);
        byteToHex[3] = convertDecToHexAscii(data_byte[i] & 0xF);
        byteToHex[4] = ' ';
        IfxAsclin_Asc_write(uartInterfaces[0].asclin, byteToHex, &cnt, TIME_INFINITE);
    }

    newLineShell();
}

static char convertDecToHexAscii(uint8_t x) {
    switch (x) {
        case 0:
        case 1:
        case 2:
        case 3:
        case 4:
        case 5:
        case 6:
        case 7:
        case 8:
        case 9:
            return x + '0';
        default:
            return x - 0xA + 'A';
    }
}

void printShellSelectPort(void) {
    int size = 6;
    IfxAsclin_Asc_write(uartInterfaces[0].asclin, "Port> ", &size, TIME_INFINITE);
}

void printShellGetCommand(void) {
    int size = 9;
    IfxAsclin_Asc_write(uartInterfaces[0].asclin, "Command> ", &size, TIME_INFINITE);
}

char receiveCharFromShell(void) {
    uint8 buf[10] = { 0, };
    int bufSize = 1;
    IfxAsclin_Asc_read(uartInterfaces[0].asclin, buf, &bufSize, TIME_INFINITE);
    if (buf[0] > 0) {
        IfxAsclin_Asc_write(uartInterfaces[0].asclin, buf, &bufSize, TIME_INFINITE);
    }

    return buf[0];
}

void newLineShell(void) {
    int size = 2;
    IfxAsclin_Asc_write(uartInterfaces[0].asclin, "\r\n", &size, TIME_INFINITE);
}

void print(char* str, int len) {
    IfxAsclin_Asc_write(uartInterfaces[0].asclin, str, &len, TIME_INFINITE);
}

/*********************************************************************************************************************/
