/**********************************************************************************************************************
 * \file CommunicationApp.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "CommunicationApp.h"
#include "ASCLIN_Shell_UART.h"
#include "Ifx_Types.h"
#include "stdint.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define ASC_TX_BUFFER_SIZE          (0x100)                                     /* Define the TX buffer size in byte    */
#define DEVICE_COUNT                (0x5)
#define MESSAGE_TYPE_COUNT          (0x10)

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/
static DeviceBuffer_t deviceBuffers[DEVICE_COUNT];
static uint8_t messageReceiver[MESSAGE_TYPE_COUNT] = {
        // For message start with 0x0X
        0x01,   //0000 0001
        // Receiver: TERMINAL

        // For message start with 0x1X
        0x03,   //0000 0011
        // Receiver: TERMINAL, STM32

        // For message start with 0x2X
        0x05,   //0000 1101
        // Receiver: TERMINAL, WROOM, RPI

        // For message start with 0x3X
        0x01,   //0000 0001
        // Receiver: TERMINAL

        // For message start with 0x4X
        0x01,   //0000 0001
        // Receiver: TERMINAL

        // For message start with 0x5X
        0x01,   //0000 0001
        // Receiver: TERMINAL

        // For message start with 0x6X
        0x01,   //0000 0001
        // Receiver: TERMINAL

        // For message start with 0x7X
        0x01,   //0000 0001
        // Receiver: TERMINAL

        // For message start with 0x8X
        0x01,   //0000 0001
        // Receiver: TERMINAL

        // For message start with 0x9X
        0x01,   //0000 0001
        // Receiver: TERMINAL

        // For message start with 0xAX
        0x05,   //0000 0101
        // Receiver: TERMINAL, RPI

        // For message start with 0xBX
        0x05,   //0000 0101
        // Receiver: TERMINAL, RPI

        // For message start with 0xCX
        0x01,   //0000 0001
        // Receiver: TERMINAL

        // For message start with 0xDX
        0x01,   //0000 0001
        // Receiver: TERMINAL

        // For message start with 0xEX
        0x01,   //0000 0001
        // Receiver: TERMINAL

        // For message start with 0xFX
        0x01,   //0000 0001
        // Receiver: TERMINAL
};

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
int convertAsciiToHex(char x);

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

void getCommandFromShell(void) {
    uint8_t buf[ASC_TX_BUFFER_SIZE] = { 0 };
    Ifx_SizeT bufCount = 0, dataSize = 0;
    char port = 1;

    printShellSelectPort();
    port = receiveCharFromShell() - '0';
    newLineShell();

    if (port < 1 || port > 2) {
        return;
    }

    printShellGetCommand();
    while (bufCount < ASC_TX_BUFFER_SIZE * 2) {
        char input = receiveCharFromShell();
        int hex = convertAsciiToHex(input);

        if (input == '\r') {
            newLineShell();
            break;
        }

        if (hex < 0) {
            newLineShell();
            return;
        }

        buf[bufCount / 2] += hex << ((bufCount % 2 == 0)? 4 : 0);
        bufCount++;
    }

    dataSize = (bufCount + 1) / 2;
    sendUart(port, buf, &dataSize);
    dataSize = (bufCount + 1) / 2;
    printUart(buf, &dataSize);
}


int convertAsciiToHex(char x) {
    switch (x) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
            return x - '0';
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f':
            return x - 'a' + 10;
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
            return x - 'A' + 10;
        default:
            return -1;
    }
}

void saveMessage(Devices_t device, uint8_t byte) {
    deviceBuffers[device].buffer[deviceBuffers[device].bufCounter++] = byte;
}


void forwardMessage(Devices_t device) {
    uint8_t messageType = deviceBuffers[device].buffer[0] >> 4;
    uint8_t* buf = deviceBuffers[device].buffer;
    uint8_t* cnt = &(deviceBuffers[device].bufCounter);

    for (int i = 0; i < 8; i++) {
        if (messageReceiver[messageType] & (1 << i)) {
            if (i == device) {
                continue;
            }
            int tempCount = *cnt;
            sendUart(i, buf, &tempCount);
        }
    }
}

void initCommunicationApp(void) {
    for (int i = 0; i < DEVICE_COUNT; i++) {
        deviceBuffers[i].bufCounter = 0;
    }
}

